# SPDX-License-Identifier: AGPL-3.0-only
# Compte de service sans aucun droit sur l'API Kubernetes : l'agent n'a rien à
# y faire, et son jeton n'est même pas monté (automountServiceAccountToken).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ameesh-agent
automountServiceAccountToken: false
